apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: stack-with-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
      service: simple-replicaset-stack
  template:
    metadata:
      labels:
        type: backend
        service: simple-replicaset-stack
        db: mongo
        language: go
    spec:
      containers:
      - name: db
        image: mongo:3.3
      - name: api
        image: vfarcic/go-demo-2
        env:
        - name: DB
          value: localhost
        livenessProbe:
          httpGet:
            path: /demo/hello
            port: 8080